name: Windows Test Report
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  org-check:
    name: Check GitHub Organization
    if: github.repository_owner == 'cognifloyd'
    runs-on: ubuntu-24.04
    steps:
      - name: Noop
        if: false
        run: |
          echo "This is a dummy step that will never run."
  report:
    runs-on: ubuntu-24.04
    needs: org-check
    steps:
    - uses: dorny/test-reporter@v2.1.1
      with:
        artifact: test-results
        name: Windows Test Results
        path: dist/test-results/unit*.xml,dist/test-results/integration*.xml
        reporter: java-junit
        list-suites: all
        list-tests: failed
        fail-on-error: false
        fail-on-empty: false
